services:
  - type: web
    name: lecture-scheduling-backend
    runtime: node
    plan: free
    autoDeploy: false
    buildCommand: |
      npm install
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
